name: its-ml-env
channels:
  - anaconda
  - defaults
dependencies:
  - pip==20.2.4
  - pip:
    - grpcio==1.34.1
    - h5py==3.1.0
    - image==1.5.27
    - imbalanced-learn==0.8.1
    - imblearn==0.0
    - importlib-metadata==1.7.0
    - importlib-resources==5.1.2
    - kapre==0.3.4
    - librosa==0.8.0
    - n2v==0.2.1
    - numpy==1.19.4
    - scikit-image==0.17.2
    - opencv-python==4.1.1.26
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - picklable-itertools==0.1.1
    - pillow==7.2.0
    - pip==21.0.1
    - plotly==4.14.3
    - pooch==1.3.0
    - prettytable==2.1.0
    - progressbar2==3.51.3
    - protobuf==3.14.0
    - py==1.9.0
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pydotplus==2.0.2
    - pytest==6.1.2
    - python-utils==2.4.0
    - scikit-learn==0.24.0
    - scikit-multilearn==0.2.0
    - scipy==1.4.1
    - setuptools==53.0.0
    - sklearn==0.0
    - soundfile==0.10.3.post1
    - sqlparse==0.3.0
    - tensorflow-gpu==2.2.0
    - termcolor==1.1.0
    - tfkerassurgeon==0.2.1
    - theano==1.0.4
    - tiffcapture==0.1.6
    - tifffile==2020.10.1
    - tikzplotlib==0.9.8
    - toml==0.10.2
    - torchsummary==1.5.1
    - torchviz==0.0.1
    - urllib3==1.26.3
